server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:~/book-my-ticket
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always 
  h2:
    console:
      path: /h2-book-my-ticket
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy