-- DROP SEQ & TABLES
DROP TABLE IF EXISTS CITY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS THEATER CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS CITY_THEATRE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS MOVIE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS THEATER_MOVIE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS SEAT CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS MOVIE_SEAT CASCADE CONSTRAINTS;

DROP SEQUENCE IF EXISTS CITY_SEQ;
DROP SEQUENCE IF EXISTS THEATER_SEQ;
DROP SEQUENCE IF EXISTS MOVIE_SEQ;
DROP SEQUENCE IF EXISTS SEAT_SEQ;


-- CREATE SEQIENCE
CREATE SEQUENCE CITY_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE THEATER_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE MOVIE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SEAT_SEQ
START WITH 1
INCREMENT BY 1;

commit;

-- CREATE TABLE
CREATE TABLE CITY(
  CITY_ID BIGINT DEFAULT CITY_SEQ.nextval PRIMARY KEY,
  CITY_NAME VARCHAR(15)
);

CREATE table THEATER (
THEATER_ID BIGINT DEFAULT THEATER_SEQ.nextval PRIMARY KEY,
THEATER_NAME VARCHAR(20),
SEATS NUMBER(3,0)
);

CREATE TABLE CITY_THEATRE (
  CITY_ID BIGINT,
  THEATER_ID BIGINT
);


CREATE table MOVIE(
  MOVIE_ID BIGINT DEFAULT MOVIE_SEQ.nextval PRIMARY KEY,
  MOVIE_NAME VARCHAR(20)
);

CREATE TABLE THEATER_MOVIE (
  THEATER_ID BIGINT,
  MOVIE_ID BIGINT
);

CREATE table SEAT(
  SEAT_ID BIGINT DEFAULT MOVIE_SEQ.nextval PRIMARY KEY,
  BOOKED VARCHAR(20),
  BOOKED_BY VARCHAR(20),
  VERSION NUMBER(3,0)
);

CREATE TABLE MOVIE_SEAT (
  MOVIE_ID BIGINT,
  SEAT_ID BIGINT
);

commit;