-- DROP SEQ & TABLES
DROP TABLE IF EXISTS CITY CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS THEATER CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS CITY_THEATRE_TABLE CASCADE CONSTRAINTS;

DROP SEQUENCE IF EXISTS CITY_SEQ;
DROP SEQUENCE IF EXISTS THEATER_SEQ;




-- CREATE SEQIENCE
CREATE SEQUENCE CITY_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE THEATER_SEQ
START WITH 1
INCREMENT BY 1;

commit;

-- CREATE TABLE
CREATE TABLE CITY(
	CITY_ID BIGINT DEFAULT CITY_SEQ.nextval PRIMARY KEY,
	CITY_NAME VARCHAR(15)
);

CREATE table THEATER (
THEATER_ID BIGINT DEFAULT THEATER_SEQ.nextval PRIMARY KEY,
THEATER_NAME VARCHAR(20)
);


commit;